baseURL = 'https://sand94.github.io'
languageCode = 'en-us'
title = 'Haritalama'
theme = 'ananke'

[params]
show_reading_time = true
body_classes = 'roboto-mono-full bg-near-white'
featured_image_class = 'contain bg-center bg-orange'
cover_dimming_class = 'bg-black-10'
post_content_classes = 'roboto-mono-full bg-near-white'
recent_posts_number = 3
custom_css = ['custom.css']


[taxonomies]
tag = "tags"
category = "categories"
journal = "journals"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
