baseURL = 'https://sand94.github.io'
languageCode = 'en-us'
title = 'Haritalama'
theme = 'ananke'

[params]
body_classes = 'avenir bg-near-white'
post_content_classes = 'avenir bg-near-white'
recent_posts_number = 3
custom_css = ['custom.css']
